### ISSUE TITLE
[BUG] Crash when opening the chat window with Tweakaroo installed

### ISSUE THREAD

**Issue by UltraBlackLinux** [DarkKronicle/AdvancedChatCore#35]
**Describe the bug**
Minecraft crashes when opening the chat window:
```
[27/02/2022 18:19:19 pm] 	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
[27/02/2022 18:19:19 pm] 	at net.minecraft.client.gui.screen.ChatScreen.handler$cmi000$storeChatText(ChatScreen:532)
[27/02/2022 18:19:19 pm] 	at net.minecraft.client.gui.screen.ChatScreen.removed(ChatScreen)
[27/02/2022 18:19:19 pm] 	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient:964)
[27/02/2022 18:19:19 pm] 	at fi.dy.masa.malilib.gui.GuiBase.openGui(GuiBase.java:649)
[27/02/2022 18:19:19 pm] 	at net.minecraft.client.gui.screen.ChatScreen.handler$zze000$chatInit(ChatScreen:1032)
[27/02/2022 18:19:19 pm] 	at net.minecraft.client.gui.screen.ChatScreen.init(ChatScreen)
[27/02/2022 18:19:19 pm] 	at net.minecraft.client.gui.screen.Screen.redirect$bko000$onInit(Screen:5271)
[27/02/2022 18:19:19 pm] 	at net.minecraft.client.gui.screen.Screen.init(Screen:388)
[27/02/2022 18:19:19 pm] 	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient:989)
[27/02/2022 18:19:19 pm] 	at net.minecraft.client.MinecraftClient.openChatScreen(MinecraftClient:954)
[27/02/2022 18:19:19 pm] 	at net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient:1882)
[27/02/2022 18:19:19 pm] 	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1729)
[27/02/2022 18:19:19 pm] 	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1086)
[27/02/2022 18:19:19 pm] 	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
[27/02/2022 18:19:19 pm] 	at net.minecraft.client.main.Main.main(Main:238)
[27/02/2022 18:19:19 pm] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[27/02/2022 18:19:19 pm] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[27/02/2022 18:19:19 pm] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[27/02/2022 18:19:19 pm] 	at java.lang.reflect.Method.invoke(Method.java:568)
[27/02/2022 18:19:19 pm] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
[27/02/2022 18:19:19 pm] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
[27/02/2022 18:19:19 pm] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Minecraft Info**
Minecraft information: 1.18.1
- AdvancedChat version 1.4.2

**To Reproduce**
Open the chat

**Additional context**
Mods used:
```
 AdvancedChatCore-1.18.1-1.4.2.jar
itemscroller-fabric-1.18.1-0.15.0.jar
 appleskin-fabric-mc1.18.1-2.3.0.jar
konkrete_fabric_1.3.3_MC_1.18-1.18.1.jar
 architectury-3.7.22.jar		
 lazydfu-0.1.2.jar
 arrp-0.5.4.jar					  
libjf-2.4.0.jar
 baritone-standalone-fabric-1.8.2.jar		 
 malilib-fabric-1.18.1-0.11.7.jar
 BetterF3-1.2.2-Fabric-1.18.jar			  
minihud-fabric-1.18.1-0.21.3.jar
 BetterThirdPerson-Forge-1.18-1.6.0.jar		  
mixintrace-1.1.0+1.17.jar
 blur-2.4.1.jar					  
moderate-loading-screen-1.1.2+1.17-1.18.jar
 c2me-fabric-mc1.18.1-0.2.0+alpha.6.55-all.jar	  
modmenu-3.0.1.jar
 chime-1.1.2.jar				  
MouseTweaks-fabric-mc1.18-2.22.jar
 CleanView-1.18.1-v1-fabric.jar			  
multiconnect-1.5.10.jar
 clear-skies-fabric-mc118-2.0.88.jar		  
notenoughcrashes-4.1.4+1.18.1-fabric.jar
 cloth-api-3.1.61.jar				  
PresenceFootsteps-1.4.0.jar
 cloth-config-6.2.57-fabric.jar			  
reeses_sodium_options-mc1.18.1-1.4.0.jar
 continuity-1.1.0+1.18.jar			  
RoughlyEnoughItems-7.3.432.jar
 cullleaves-2.3.2.jar				  
slotlock-1.0.4-BETA+1.18.jar
 cullparticles-2.0.jar				  
smoothboot-fabric-1.18-1.7.0.jar
 customfov-fabric-1.4.1-1.18.1.jar		  
sodium-extra-mc1.18.1-0.4.0.jar
'EvergreenHUD (1.4.0.0-rev.641c7c4).jar'	  
sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar
 fabric-api-0.46.4+1.18.jar			  
soundphysics-fabric-1.18.1-1.0.4.jar
 fabric-language-kotlin-1.7.1+kotlin.1.6.10.jar   
spark-1.8.6-fabric.jar
 fancymenu_fabric_2.6.3_MC_1.18-1.18.1.jar	  
starlight-1.0.1+fabric.0583973.jar
 ferritecore-4.1.2-fabric.jar			  
TieFix-1.9.0.jar
 FpsReducer-fabric-1.25-mc1.18.jar		  
tweakeroo-fabric-1.18.1-0.12.3.jar
 hatlist-1.2.jar				  
Xaeros_Minimap_FP22.2.0.1_Fabric_1.18.jar
 held-item-info-1.2.0.jar			  
XaerosWorldMap_1.20.3.1_Fabric_1.18.jar
 InGameAccountSwitcher-Fabric-1.18-7.1.3.jar	 
 Zoomify-1.1.0.jar
 iris-mc1.18.1-1.2.0-pre.jar
```

**Comment by UltraBlackLinux** [comment]
Okay it seems to be incompatible with Tweakeroo - I would really like to have this resolved as I use Tweakeroo a lot

**Comment by UltraBlackLinux** [comment]
https://github.com/DarkKronicle/AdvancedChatCore/issues/13

Why do people never edit the title of their bugreport

**Comment by DarkKronicle** [comment]
I'll rename that bug report. Yeah, you just have to turn off persistent text in tweakaroo but AdvancedChat has it's own
